server:
  port: 8080
  servlet:
    context-path: /apis

spring:
  data:
    redis:
      host: 101.132.251.133
      port: 6380
      password: KindstaridRFl#T%231
      database: 8

coldlight:
  token:
    secret: 45451165465
  security:
    global-white-list:
      - "/login"
      - "/public/**"
      - "/actuator/health"